[package]
name = "diesel_full_text_search"
version = "2.0.0"
description = "Adds support for PostgreSQL full text search to Diesel"
license = "MIT"
repository = "https://github.com/diesel-rs/diesel_full_text_search"

[dependencies]
diesel = { path = "../diesel/diesel", features = ["postgres"], default-features = false }
